//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _01.DayOfTheWeek.Client.DayOfTheWeekService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DayOfTheWeekService.IServiceDayGetter")]
    public interface IServiceDayGetter {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDayGetter/GetDay", ReplyAction="http://tempuri.org/IServiceDayGetter/GetDayResponse")]
        System.DayOfWeek GetDay(System.DateTime day);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDayGetter/GetDay", ReplyAction="http://tempuri.org/IServiceDayGetter/GetDayResponse")]
        System.Threading.Tasks.Task<System.DayOfWeek> GetDayAsync(System.DateTime day);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceDayGetterChannel : _01.DayOfTheWeek.Client.DayOfTheWeekService.IServiceDayGetter, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDayGetterClient : System.ServiceModel.ClientBase<_01.DayOfTheWeek.Client.DayOfTheWeekService.IServiceDayGetter>, _01.DayOfTheWeek.Client.DayOfTheWeekService.IServiceDayGetter {
        
        public ServiceDayGetterClient() {
        }
        
        public ServiceDayGetterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDayGetterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDayGetterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDayGetterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.DayOfWeek GetDay(System.DateTime day) {
            return base.Channel.GetDay(day);
        }
        
        public System.Threading.Tasks.Task<System.DayOfWeek> GetDayAsync(System.DateTime day) {
            return base.Channel.GetDayAsync(day);
        }
    }
}
