#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using _01.PleaseWork;

namespace _01.PleaseWork	
{
	public partial class Category
	{
		private int _categoryID;
		public virtual int CategoryID
		{
			get
			{
				return this._categoryID;
			}
			set
			{
				this._categoryID = value;
			}
		}
		
		private string _categoryName;
		public virtual string CategoryName
		{
			get
			{
				return this._categoryName;
			}
			set
			{
				this._categoryName = value;
			}
		}
		
		private string _imageFileName;
		public virtual string ImageFileName
		{
			get
			{
				return this._imageFileName;
			}
			set
			{
				this._imageFileName = value;
			}
		}
		
		private IList<RentalRate> _rentalRates = new List<RentalRate>();
		public virtual IList<RentalRate> RentalRates
		{
			get
			{
				return this._rentalRates;
			}
		}
		
		private IList<Car> _cars = new List<Car>();
		public virtual IList<Car> Cars
		{
			get
			{
				return this._cars;
			}
		}
		
	}
}
#pragma warning restore 1591
