#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using _01.PleaseWork;

namespace _01.PleaseWork	
{
	public partial class RentalRate
	{
		private int _rentalRateID;
		public virtual int RentalRateID
		{
			get
			{
				return this._rentalRateID;
			}
			set
			{
				this._rentalRateID = value;
			}
		}
		
		private int? _categoryID;
		public virtual int? CategoryID
		{
			get
			{
				return this._categoryID;
			}
			set
			{
				this._categoryID = value;
			}
		}
		
		private decimal? _daily;
		public virtual decimal? Daily
		{
			get
			{
				return this._daily;
			}
			set
			{
				this._daily = value;
			}
		}
		
		private decimal? _weekly;
		public virtual decimal? Weekly
		{
			get
			{
				return this._weekly;
			}
			set
			{
				this._weekly = value;
			}
		}
		
		private decimal? _monthly;
		public virtual decimal? Monthly
		{
			get
			{
				return this._monthly;
			}
			set
			{
				this._monthly = value;
			}
		}
		
		private Category _category;
		public virtual Category Category
		{
			get
			{
				return this._category;
			}
			set
			{
				this._category = value;
			}
		}
		
	}
}
#pragma warning restore 1591
