#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace _02.PleaseNorhtwindWork	
{
	public partial class Contact
	{
		private int _contactID;
		public virtual int ContactID
		{
			get
			{
				return this._contactID;
			}
			set
			{
				this._contactID = value;
			}
		}
		
		private string _contactType;
		public virtual string ContactType
		{
			get
			{
				return this._contactType;
			}
			set
			{
				this._contactType = value;
			}
		}
		
		private string _companyName;
		public virtual string CompanyName
		{
			get
			{
				return this._companyName;
			}
			set
			{
				this._companyName = value;
			}
		}
		
		private string _contactName;
		public virtual string ContactName
		{
			get
			{
				return this._contactName;
			}
			set
			{
				this._contactName = value;
			}
		}
		
		private string _contactTitle;
		public virtual string ContactTitle
		{
			get
			{
				return this._contactTitle;
			}
			set
			{
				this._contactTitle = value;
			}
		}
		
		private string _address;
		public virtual string Address
		{
			get
			{
				return this._address;
			}
			set
			{
				this._address = value;
			}
		}
		
		private string _city;
		public virtual string City
		{
			get
			{
				return this._city;
			}
			set
			{
				this._city = value;
			}
		}
		
		private string _region;
		public virtual string Region
		{
			get
			{
				return this._region;
			}
			set
			{
				this._region = value;
			}
		}
		
		private string _postalCode;
		public virtual string PostalCode
		{
			get
			{
				return this._postalCode;
			}
			set
			{
				this._postalCode = value;
			}
		}
		
		private string _country;
		public virtual string Country
		{
			get
			{
				return this._country;
			}
			set
			{
				this._country = value;
			}
		}
		
		private string _phone;
		public virtual string Phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				this._phone = value;
			}
		}
		
		private string _extension;
		public virtual string Extension
		{
			get
			{
				return this._extension;
			}
			set
			{
				this._extension = value;
			}
		}
		
		private string _fax;
		public virtual string Fax
		{
			get
			{
				return this._fax;
			}
			set
			{
				this._fax = value;
			}
		}
		
		private string _homePage;
		public virtual string HomePage
		{
			get
			{
				return this._homePage;
			}
			set
			{
				this._homePage = value;
			}
		}
		
		private string _photoPath;
		public virtual string PhotoPath
		{
			get
			{
				return this._photoPath;
			}
			set
			{
				this._photoPath = value;
			}
		}
		
		private byte[] _photo;
		public virtual byte[] Photo
		{
			get
			{
				return this._photo;
			}
			set
			{
				this._photo = value;
			}
		}
		
	}
}
#pragma warning restore 1591
