var names = new Array();
var links = new Array();

names[0] = "preface";
names[1] = "introProgramming1";
names[2] = "introProgramming2";
names[3] = "variables1";
names[4] = "variables2";
names[5] = "operators1";
names[6] = "operators2";
names[7] = "console1";
names[8] = "console2";
names[9] = "console3";
names[10] = "conditional1";
names[11] = "conditional2";
names[12] = "loops1";
names[13] = "loops2";
names[14] = "arrays1";
names[15] = "arrays2";
names[16] = "numeralSystems1";
names[17] = "numeralSystems2";
names[18] = "methods1";
names[19] = "methods2";
names[20] = "recursion1";
names[21] = "recursion2";
names[22] = "recursion3";
names[23] = "objects1";
names[24] = "objects2";
names[25] = "exception1";
names[26] = "exception2";
names[27] = "strings1";
names[28] = "strings2";
names[29] = "classes1-1";
names[30] = "classes1-2";
names[31] = "classes1-3";
names[32] = "classes2-1";
names[33] = "classes2-2";
names[34] = "textFiles1";
names[35] = "textFiles2";
names[36] = "dataStructures1";
names[37] = "dataStructures2";
names[38] = "dataStructures3";
names[39] = "graphs1";
names[40] = "graphs2";
names[41] = "dictionaries1";
names[42] = "dictionaries2";
names[43] = "algo1";
names[44] = "algo2";
names[45] = "oop1";
names[46] = "oop2";
names[47] = "quality1";
names[48] = "quality2";
names[49] = "linq1";
names[50] = "linq2";
names[51] = "problemSolving1";
names[52] = "problemSolving2";
names[53] = "sampleExams1";
names[54] = "sampleExams2";
names[55] = "sampleExams3";
names[56] = "sampleExams4";
names[57] = "sampleExams5";
names[58] = "sampleExams6";
names[59] = "summary1";
names[60] = "summary2";

links[0] = "mindmap-preview.html?image=team_4_preface_chapter_0.png&title=Preface"; //+
links[1] = "mindmap-preview.html?image=team_6_introToPrograming_chapter_1.png&title=Intro to Programming Map 1"; //+
links[2] = "mindmap-preview.html?image=team_8_introToPrograming_chapter_1.png&title=Intro to Programming Map 2";
links[3] = "mindmap-preview.html?image=team_60_variables_chapter_2.png&title=Types and Variables Map 1";
links[4] = "mindmap-preview.html?image=team_62_variables_chapter_2.png&title=Types and Variables Map 2";
links[5] = "mindmap-preview.html?image=team_96_operators_chapter_3.png&title=Operators and Expressions Map 1";
links[6] = "mindmap-preview.html?image=team_98_operators_chapter_3.jpg&title=Operators and Expressions Map 2";
links[7] = "mindmap-preview.html?image=team_100_console_chapter_4.png&title=Console Input Output Map 1 ";
links[8] = "mindmap-preview.html?image=team_102_console_chapter_4.png&title=Console Input Output Map 2 ";
links[9] = "mindmap-preview.html?image=team_104_console_chapter_4.png&title=Console Input Output Map 3 ";
links[10] = "mindmap-preview.html?image=team_106_conditionals_chapter_5.jpg&title=Conditional Statements Map 1";
links[11] = "mindmap-preview.html?image=team_108_conditionals_chapter_5.png&title=Conditional Statements Map 2";
links[12] = "mindmap-preview.html?image=team_110_loops_chapter_6.png&title=Loops Map 1";
links[13] = "mindmap-preview.html?image=team_112_loops_chapter_6.png&title=Loops Map 2";
links[14] = "mindmap-preview.html?image=team_114_arrays_chapter_7.png&title=Arrays Map 1";
links[15] = "mindmap-preview.html?image=team_116_arrays_chapter_7.png&title=Arrays Map 2";
links[16] = "mindmap-preview.html?image=team_120_numSystems_chapter_8.png&title=Numeral Systems Map 1";
links[17] = "mindmap-preview.html?image=team_122_numSystems_chapter_8.png&title=Numeral Systems Map 2";
links[18] = "mindmap-preview.html?image=team_124_methods_chapter_9.png&title=Methods Map 1";
links[19] = "mindmap-preview.html?image=team_126_methods_chapter_9.jpg&title=Methods Map 2";
links[20] = "mindmap-preview.html?image=team_10_recursion_chapter_10.png&title=Recursion Map 1";
links[21] = "mindmap-preview.html?image=team_12_recursion_chapter_10.png&title=Recursion Map 2";
links[22] = "mindmap-preview.html?image=team_14_recursion_chapter_10.png&title=Recursion Map 3";
links[23] = "mindmap-preview.html?image=team_16_usingObjects_chapter_11.png&title=Using Objects Map 1";
links[24] = "mindmap-preview.html?image=team_18_usingObjects_chapter_11.png&title=Using Objects Map 2";
links[25] = "mindmap-preview.html?image=team_20_Exceptions_chapter_12.png&title=Exception Handling Map 1";
links[26] = "mindmap-preview.html?image=team_22_Exceptions_chapter_12.png&title=Exception Handling Map 2";
links[27] = "mindmap-preview.html?image=team_24_strings_chapter_13.png&title=Strings and Text Processing Map 1";
links[28] = "mindmap-preview.html?image=team_26_strings_chapter_13.png&title=Strings and Text Processing Map 2";
links[29] = "mindmap-preview.html?image=team_28_Classes_chapter_14.1.png&title=Defining Classes Part 1 Map 1";
links[30] = "mindmap-preview.html?image=team_30_Classes_chapter_14.1.png&title=Defining Classes Part 1 Map 2";
links[31] = "mindmap-preview.html?image=team_32_Classes_chapter_14.1.png&title=Defining Classes Part 1 Map 3";
links[32] = "mindmap-preview.html?image=team_34_Classes_chapter_14.2.png&title=Defining Classes Part 2 Map 1";
links[33] = "mindmap-preview.html?image=team_36_Classes_chapter_14.2.png&title=Defining Classes Part 2 Map 2";
links[34] = "mindmap-preview.html?image=team_38_textFiles_chapter_15.png&title=Text Files Map 1";
links[35] = "mindmap-preview.html?image=team_40_textFiles_chapter_15.png&title=Text Files Map 2";
links[36] = "mindmap-preview.html?image=team_42_dataStruct_chapter_16.png&title=Linear Data Structures Map 1";
links[37] = "mindmap-preview.html?image=team_44_dataStruct_chapter_16.png&title=Linear Data Structures Map 2";
links[38] = "mindmap-preview.html?image=team_46_dataStruct_chapter_16.png&title=Linear Data Structures Map 3";
links[39] = "mindmap-preview.html?image=team_48_graphs_chapter_16.png&title=Trees and Graphs Map 1";
links[40] = "mindmap-preview.html?image=team_50_graphs_chapter_16.png&title=Trees and Graphs Map 2";
links[41] = "mindmap-preview.html?image=team_52_dicts_chapter_18.png&title=Dict. , Hash-Tables and Sets Map 1";
links[42] = "mindmap-preview.html?image=team_54_dicts_chapter_18.png&title=Dict. , Hash-Tables and Sets Map 2";
links[43] = "mindmap-preview.html?image=team_56_algo1_chapter_19.png&title=Data Str. and Alg. Complex. Map 1";
links[44] = "mindmap-preview.html?image=team_58_algo1_chapter_19.jpg&title=Data Str. and Alg. Complex. Map 2";
links[45] = "mindmap-preview.html?image=team_66_oop_chapter_20.png&title=OOP Principles Map 2";
links[46] = "mindmap-preview.html?image=team_68_oop_chapter_20.png&title=OOP Principles Map 3";
links[47] = "mindmap-preview.html?image=team_70_quality_chapter_21.jpg&title=High-Quality Prog. Code Map 1";
links[48] = "mindmap-preview.html?image=team_72_quality_chapter_21.png&title=High-Quality Prog. Code Map 2";
links[49] = "mindmap-preview.html?image=team_74_linq_chapter_22.png&title=Lambdas and LINQ Queries Map 1";
links[50] = "mindmap-preview.html?image=team_76_linq_chapter_22.png&title=Lambdas and LINQ Queries Map 2";
links[51] = "mindmap-preview.html?image=team_78_problemSolving_chapter_23.png&title=Prob. Solving Methodology Map 1";
links[52] = "mindmap-preview.html?image=team_80_problemSolving_chapter_23.png&title=Prob. Solving Methodology Map 2";
links[53] = "mindmap-preview.html?image=team_84_sampleExam_chapter_24.png&title=Sample Exam – Topic #1, Map 1";
links[54] = "mindmap-preview.html?image=team_86_sampleExam_chapter_24.png&title=Sample Exam – Topic #1, Map 2";
links[55] = "mindmap-preview.html?image=team_88_sampleExam_chapter_25.png&title=Sample Exam – Topic #1, Map 3";
links[56] = "mindmap-preview.html?image=team_90_sampleExam_chapter_25.png&title=Sample Exam – Topic #1, Map 4";
links[57] = "mindmap-preview.html?image=team_92_sampleExam_chapter_26.png&title=Sample Exam – Topic #1, Map 5";
links[58] = "mindmap-preview.html?image=team_94_sampleExam_chapter_26.jpg&title=Sample Exam – Topic #1, Map 6";
links[59] = "mindmap-preview.html?image=team_128_bookSum_chapter_00.png&title=Book Summary Map 1";
links[60] = "mindmap-preview.html?image=team_130_bookSum_chapter_00.png&title=Book Summary Map 2";

function SetLinks () {
	for (var i = names.length - 1; i >= 0; i--) {
		var element = document.getElementsByName(names[i]);
		for (var j = element.length - 1; j >= 0; j--) {
			element[j].href= links[i]};
		}
	};
